spring.application.name=ORDER-SERVICE

server.port=8082

user.service.url=http://localhost:8081

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# H2 Database
spring.datasource.url=jdbc:h2:mem:ordersdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Resilience4j Circuit Breaker - Payment Service
resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=5
resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=2

# Day 8 - User Service Circuit Breaker
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=2

# Day 8 - User Service Retry
resilience4j.retry.instances.userService.max-attempts=3
resilience4j.retry.instances.userService.wait-duration=500ms

# Day 9 - User Service Bulkhead
resilience4j.bulkhead.instances.userService.max-concurrent-calls=2
resilience4j.bulkhead.instances.userService.max-wait-duration=0